apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-volume
  labels: 
    type: local
spec:
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath