apiVersion: v1
kind: Service
metadata:
  name: homeassistant-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - name: homeassistant
      port: 8123
      targetPort: homeassistant
      nodePort: 32222