apiVersion: v1
kind: Service
metadata:
  name: pihole-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
    - name: pihole-admin
      port: 80
      nodePort: 30800
    - name: dns-tcp
      targetPort: 53
      protocol: TCP
      port: 53
    - name: dns-udp
      targetPort: 53
      protocol: UDP
      port: 53
  externalIPs:
    - 192.168.200.231