apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piholeconf-local-claim
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piholednsmasq-local-claim
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce