# Create both persistant volumes for pihole
# Files: dnsmasq and piholeconf

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-conf-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /mnt/blue_lightsaber/double_blade/kube/pihole/piholeconf
    server: 192.168.50.150

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /mnt/blue_lightsaber/double_blade/kube/pihole/dnsmasq
    server: 192.168.50.150