apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-conf-pvc
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
