apiVersion: v1
kind: PersistentVolume
metadata:
  name: piholeconf-local-volume
  labels: 
    type: local
spec:
  hostPath:
    path: "/mnt/pihole/piholeconf"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: piholednsmasq-local-volume
  labels: 
    type: local
spec:
  hostPath:
    path: "/mnt/pihole/dnsmasq"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath